services:
  cgit:
    image: ghcr.io/zopiya/cgit:latest
    container_name: cgit
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Asia/Shanghai"
    volumes:
      - ./repos:/repos:ro
      - ./cache:/var/cache/cgit
    ports:
      - "8080:8080"

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
